include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - always_use_package_imports
    - annotate_overrides
    - avoid_empty_else
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_return_types_on_setters
    - avoid_unnecessary_containers
    - await_only_futures
    - cancel_subscriptions
    - curly_braces_in_flow_control_structures
    - empty_catches
    - empty_constructor_bodies
    - eol_at_end_of_file
    - file_names
    - hash_and_equals
    - lines_longer_than_80_chars: false
    - no_duplicate_case_values
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_single_quotes
    - sized_box_for_whitespace
    - sort_child_properties_last
    - unnecessary_const
    - unnecessary_new
    - unnecessary_this
    - use_key_in_widget_constructors
    - use_super_parameters
