import 'package:flutter/material.dart';

/// Maps icon name strings (from category constants) to Flutter [IconData].
class IconHelper {
  static IconData fromName(String name) {
    return _map[name] ?? Icons.category_outlined;
  }

  static const Map<String, IconData> _map = {
    'shopping_cart': Icons.shopping_cart,
    'local_cafe': Icons.local_cafe,
    'electric_rickshaw': Icons.electric_rickshaw,
    'local_taxi': Icons.local_taxi,
    'directions_bus': Icons.directions_bus,
    'local_gas_station': Icons.local_gas_station,
    'lunch_dining': Icons.lunch_dining,
    'home': Icons.home,
    'bolt': Icons.bolt,
    'water_drop': Icons.water_drop,
    'smartphone': Icons.smartphone,
    'wifi': Icons.wifi,
    'school': Icons.school,
    'local_hospital': Icons.local_hospital,
    'medication': Icons.medication,
    'checkroom': Icons.checkroom,
    'card_giftcard': Icons.card_giftcard,
    'temple_hindu': Icons.temple_hindu,
    'movie': Icons.movie,
    'shopping_bag': Icons.shopping_bag,
    'account_balance': Icons.account_balance,
    'security': Icons.security,
    'trending_up': Icons.trending_up,
    'diamond': Icons.diamond,
    'cleaning_services': Icons.cleaning_services,
    'propane_tank': Icons.propane_tank,
    'spa': Icons.spa,
    'content_cut': Icons.content_cut,
    'fitness_center': Icons.fitness_center,
    'more_horiz': Icons.more_horiz,
    'account_balance_wallet': Icons.account_balance_wallet,
    'work': Icons.work,
    'store': Icons.store,
    'savings': Icons.savings,
    'pie_chart': Icons.pie_chart,
    'apartment': Icons.apartment,
    'currency_rupee': Icons.currency_rupee,
    'redeem': Icons.redeem,
    'category': Icons.category,
    'receipt': Icons.receipt,
    'restaurant': Icons.restaurant,
    'fastfood': Icons.fastfood,
    'flight': Icons.flight,
    'hotel': Icons.hotel,
    'sports': Icons.sports,
    'pets': Icons.pets,
    'child_care': Icons.child_care,
    'elderly': Icons.elderly,
    'subscriptions': Icons.subscriptions,
    'games': Icons.games,
    'music_note': Icons.music_note,
    'book': Icons.book,
    'headphones': Icons.headphones,
    'credit_card': Icons.credit_card,
    'money': Icons.money,
    'attach_money': Icons.attach_money,
    'trending_down': Icons.trending_down,
    'swap_horiz': Icons.swap_horiz,
    'local_parking': Icons.local_parking,
    'menu_book': Icons.menu_book,
    'groups': Icons.groups,
    'local_laundry_service': Icons.local_laundry_service,
    'tv': Icons.tv,
    'receipt_long': Icons.receipt_long,
    'stars': Icons.stars,
    'replay': Icons.replay,
    'handshake': Icons.handshake,
    'mic': Icons.mic,
    'camera_alt': Icons.camera_alt,
    'add': Icons.add,
  };
}
