import 'package:riverpod_annotation/riverpod_annotation.dart';

import 'package:paisa_track/core/constants/category_constants.dart';
import 'package:paisa_track/core/enums/subscription_tier.dart';

part 'smart_budget_provider.g.dart';

/// A suggestion generated by analysing past spending.
class BudgetSuggestion {
  const BudgetSuggestion({
    required this.categoryId,
    required this.categoryName,
    required this.categoryIcon,
    required this.monthlyAverage,
    required this.suggestedLimit,
    required this.lastThreeMonths,
  });

  /// The category this suggestion targets.
  final String categoryId;

  /// Display name for the category.
  final String categoryName;

  /// Icon name for the category.
  final String categoryIcon;

  /// Average monthly spend over the last 3 months.
  final double monthlyAverage;

  /// Suggested budget limit (average + 10% buffer).
  final double suggestedLimit;

  /// Spending totals for each of the last 3 months (oldest first).
  final List<double> lastThreeMonths;
}

/// Analyses the last 3 months of spending and suggests per-category budgets.
///
/// This provider is **premium-only**. Free-tier users will receive an
/// [UnsupportedError].
@riverpod
Future<List<BudgetSuggestion>> smartBudgetSuggestions(
  SmartBudgetSuggestionsRef ref,
) async {
  // TODO: Replace with actual subscription tier provider.
  const tier = SubscriptionTier.free;

  if (tier.isFree) {
    throw UnsupportedError(
      'Smart Budget suggestions require a Premium subscription.',
    );
  }

  // Simulate analysis delay.
  await Future<void>.delayed(const Duration(seconds: 2));

  // TODO: Replace with actual BudgetAnalysisService that queries
  // transactions from the last 3 months and groups by category.
  final now = DateTime.now();
  final threeMonthsAgo = DateTime(now.year, now.month - 3, 1);

  // Placeholder: Build suggestions from default expense categories
  // with mock spending data. Replace with real transaction aggregation.
  final suggestions = <BudgetSuggestion>[];

  for (final category in CategoryConstants.defaultExpenseCategories.take(8)) {
    // TODO: Query real spending per category for months
    // [threeMonthsAgo .. now].
    final month1 = 0.0;
    final month2 = 0.0;
    final month3 = 0.0;
    final avg = (month1 + month2 + month3) / 3;

    if (avg <= 0) continue;

    suggestions.add(BudgetSuggestion(
      categoryId: category.id,
      categoryName: category.name,
      categoryIcon: category.iconName,
      monthlyAverage: avg,
      suggestedLimit: (avg * 1.10).ceilToDouble(), // +10% buffer
      lastThreeMonths: [month1, month2, month3],
    ));
  }

  // Keep reference to suppress unused variable warning.
  assert(threeMonthsAgo.isBefore(now));

  return suggestions;
}
